<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
      <PackageReference Include="FluentValidation" Version="11.8.0" />
      <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.8.0" />
      <PackageReference Include="Mapster" Version="7.4.0" />
      <PackageReference Include="Mapster.Async" Version="2.0.1" />
      <PackageReference Include="Mapster.Core" Version="1.2.1" />
      <PackageReference Include="Mapster.DependencyInjection" Version="1.0.1" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BG.NET.Library.DataAccessLayer\BG.NET.Library.DataAccess.csproj" />
      <ProjectReference Include="..\BG.NET.Library.Models\BG.NET.Library.Models.csproj" />
    </ItemGroup>

</Project>
