<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Dto\Auth\" />
      <Folder Include="Entities\Auth\" />
      <Folder Include="Entities\Library\" />
    </ItemGroup>

</Project>
